function label = manuscript_policy_map(pol_id)
% MANUSCRIPT_POLICY_MAP  
%
%   label = manuscript_policy_map('pol3')   gives 'Policy 3'
%

MAP = struct( ...
    'pol1', 'Policy 1', ...
    'pol2', 'Policy 2', ...
    'pol3', 'Policy 3', ...
    'pol4', 'Policy 4', ...
    'pol5', 'Policy 5', ...
    'pol6', 'Policy 6');

if ~ischar(pol_id) || ~isfield(MAP, pol_id)
    error(['manuscript_policy_map: unrecognized pol_id ''%s''. ' ...
           'Valid: pol1, pol2, pol3, pol4, pol5, pol6.'], ...
           num2str(pol_id));
end

label = MAP.(pol_id);

end
